### ISSUE TITLE
Use MSYSTEM_PREFIX

### ISSUE THREAD

**Issue by silverqx** [Chocobo1/setup-ccache-action#5]
Hi @Chocobo1, thx for the great GH action.

This line:
https://github.com/Chocobo1/setup-ccache-action/blob/8856534dac357009109dfd78c66a872bd81d03a9/src/utils.ts#L72

should be? `MINGW_PREFIX` or `MSYSTEM_PREFIX`:
`return ${Process.env.MINGW_PREFIX}/lib/ccache/bin;`

Currently, it is `${Process.env.MSYSTEM}`, so the path will be `/UCRT64/lib/ccache/bin`.
With `MSYSTEM_PREFIX` it will be `/ucrt64/lib/ccache/bin`.
I think that the `MSYSTEM` env. variable is not supposed to be used in paths, that is why `MSYSTEM_PREFIX` exists.

Here is source where it is [defined](https://github.com/msys2/MSYS2-packages/blob/master/filesystem/msystem) and link to all [occurrences](https://github.com/msys2/MSYS2-packages/search?q=MINGW_PREFIX).

Later: Also when I looked at GHA output log I have found two more cases where this upper-case `UCRT64` is used:
```
Clear ccache statistics
Prepend ccache symlinks path to $PATH
  ccache symlinks path (msys): "/UCRT64/lib/ccache/bin"
  (msys) PATH=/UCRT64/lib/ccache/bin:/ucrt64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
Create environment variables
  ${{ env.ccache_symlinks_path }} = /UCRT64/lib/ccache/bin
```

So it should be changed for `env.ccache_symlinks_path` output variable and in prepend path too.

I'm not sure what is the difference between `MSYSTEM_PREFIX` and `MINGW_PREFIX`, or which one should be used when 🙂, if you want I can ask at the msys2 issue tracker.

**Comment by Chocobo1** [comment]
>Hi @Chocobo1, thx for the great GH action.

You are welcome.

> should be? `MINGW_PREFIX` or `MSYSTEM_PREFIX`:
> `return ${Process.env.MINGW_PREFIX}/lib/ccache/bin;`

That probably would be good, applied in 243d0770d62dcff499105d7b2c4e35fa0f6b53d8.

>I'm not sure what is the difference between MSYSTEM_PREFIX and MINGW_PREFIX

Looks like `MINGW_PREFIX` is just an alias for `MSYSTEM_PREFIX`.

Also note that the msys testing CI is broken currently and I have no idea what caused it, it was working fine a few days ago. Last working instance: https://github.com/Chocobo1/setup-ccache-action/actions/runs/1458477952
I tried to replicate locally but it fails to show the symptom, i.e. it was working fine locally. 

So msys support currently is in a perverted state and I cannot fully guarantee that it is working...

**Comment by silverqx** [comment]
Thank you, for the patch.

I have setup it yesterday and it works for me, invoked like this:
```
    - name: ccache setup 🕺
      uses: Chocobo1/setup-ccache-action@v1
      with:
        windows_compile_environment: msys2
        prepend_symlinks_to_path: false
        install_ccache: false
        update_packager_index: false
        ccache_options: |
          compiler_check = %compiler% -v
          compression = false
          max_size = 3G
```

We will see, I don't know why it is failing when I have a problem like, then I use this after failing action:
```
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

    - run: exit 1
```

Then ssh into the runner and try to invoke commands directly in the runner, but it looks like that fail exits the whole job so what I'm writing above will be useless for you.
