### ISSUE TITLE
Windows msvc support

### ISSUE THREAD

**Issue by silverqx** [Chocobo1/setup-ccache-action#8]
Hi choco 👋,

this week I have set up the `ccache` for all my Windows msvc toolchains, it has **100% cache hits** and now I want to also set up the ccache for my Windows msvc related GitHub actions.

The following doesn't work, it quits with the `Warning: "windows_compile_environment=" is not supported. No operation...`:
```
    - name: ccache install 🥳
      run: |
        choco install ccache -y

    - name: ccache setup 🕺
      uses: Chocobo1/setup-ccache-action@v1
      with:
        prepend_symlinks_to_path: false
        install_ccache: false
        update_packager_index: false
        ccache_options: |
          compression = false
          max_size = 1G
```

I don't ask for full msvc support, even the `install_ccache` may not work.

Would be good to normally continue if the `windows_compile_environment` is empty or `windows_compile_environment=msvc`.

I have tried following inside the `Windows-2019` GitHub action's image, I'm posting here notes to make it easier for you:
- The `ccache --set-config xx=yy` works out of the box if the `ccache` is already installed.
- it creates `ccache.conf` file at `$env:APPDATA/ccache/ccache.conf` (~/AppData/Roaming/ccache)
- choco installs `ccache.exe` at `C:\ProgramData\chocolatey\bin\ccache.exe` and it's on the system path

I think it would be enough to make it work inside the `Windows-2019/2022` images.

[Here](https://github.com/silverqx/TinyORM/blob/main/cmake/CommonModules/TinyHelpers.cmake#L314-L401) is my cmake code that fixes/allows 100% ccache hits, it simply disables precompiled headers and replaces `/Zi` compiler option with the `/Z7` in `CMAKE_<C|CXX>_FLAGS_<CONFIG>` flags.
The Cmake defaults to `/Zi` so it has 100% ccache misses because ccache doesn't support `/Zi` but it works great with the `/Z7` compiler option. And also ccache doesn't support precompiled headers on Windows msvc.
